version: "3"

services:
  nodejs:
    build:
      context: ./Filter
    image: node-js
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - nats

  nats:
    image: nats
    container_name: nats
    restart: unless-stopped
    networks:
      - my-network

  python-app:
    build: ./Dashboard
    container_name: python-app
    restart: unless-stopped
    networks:
      - my-network
    depends_on:
      - nats

  nodejs-app2:
    build:
      context: ./Command
    image: node-js-app2
    container_name: node-js-app2
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - my-custom-mosquitto

  my-custom-mosquitto:  
    image: my-custom-mosquitto  
    container_name: my-custom-mosquitto 
    restart: unless-stopped
    ports:
      - "1883:1883"
    networks:
      - my-network

  send:
    build:
      context: ./SendData
    image: send-app
    container_name: send-app
    restart: unless-stopped
    networks:
      - my-network
    depends_on:
      - my-custom-mosquitto
      - nodejs-app2  # Update dependency to use your custom service

networks:
  my-network:
    external: true
